🚑 fix: Handle failure to download or unzip model in Dockerfile

diff --git a/cwe_api/Dockerfile b/cwe_api/Dockerfile
--- a/cwe_api/Dockerfile
+++ b/cwe_api/Dockerfile
@@ -15,6 +15,7 @@ RUN if [ ! -d modelo_cwe ]; then \
       echo "modelo_cwe not found. Downloading it..."; \
       wget "https://drive.usercontent.google.com/download?id=1KBoB-iLT3-2HJqMvXucMuh3Wi_r0ngP-&export=download&confirm=" -O modelo_cwe.zip \
       && unzip modelo_cwe.zip && rm modelo_cwe.zip \
+      || { echo "Failed to download or unzip model"; exit 1; } \
     fi
 
 RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
