fix: insecure bash command

diff --git a/cwe_api/Dockerfile b/cwe_api/Dockerfile
--- a/cwe_api/Dockerfile
+++ b/cwe_api/Dockerfile
@@ -26,11 +26,15 @@ RUN if [ ! -d modelo_cwe ]; then \
     fi
 
 RUN if [ ! -d utils ]; then \
-      echo "utils folder (cvss model) not found. Downloading it..."; \
-      wget --progress=bar:force "$CVSS_MODEL_URL" -O modelo_cvss.zip \
-      && unzip modelo_cvss.zip && rm modelo_cvss.zip \
-      || { echo "Failed to download or unzip model"; exit 1; } \
-    fi
+    echo "utils folder (cvss model) not found. Downloading it..."; \
+    if wget --progress=bar:force "$CVSS_MODEL_URL" -O modelo_cvss.zip && \
+      unzip modelo_cvss.zip && rm modelo_cvss.zip; then \
+      echo "CVSS model downloaded and extracted successfully"; \
+    else \
+      echo "Failed to download or unzip CVSS model"; \
+      exit 1; \
+    fi; \
+fi
 
 EXPOSE 8000
 
